name: custom_barcode_scanner
description: "A Flutter package for scanning barcodes and QR codes using the device camera, with support for customizable overlays."
version: 0.0.2
homepage: https://github.com/Dsachith/bar_code_scanner

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # Add any assets or fonts here if necessary
